[package]
name = "nightcycle/package"
description = "A package!"
version = "0.1.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
Future = "nightcycle/future@^0"
Result = "nightcycle/result@^0"
Option = "nightcycle/option@^0"
SerdeJson = "nightcycle/serde-json@^0"
NetworkUtil = "nightcycle/network-util@2.1.0"
HashUtil = "boatbomber/hashlib@1.0.0"
